apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2024-09-15T15:15:22Z"
  generateName: guestbook-ui-649789b49c-
  labels:
    app: guestbook-ui
    pod-template-hash: 649789b49c
  name: guestbook-ui-649789b49c-58plk
  namespace: default
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicaSet
    name: guestbook-ui-649789b49c
    uid: e68dcefd-5639-4820-a795-309020954a21
  resourceVersion: "3491"
  uid: c0aa353e-cd57-4126-b02d-d7ab5a73eb01
spec:
  containers:
  - image: gcr.io/heptio-images/ks-guestbook-demo:0.2
    imagePullPolicy: IfNotPresent
    name: guestbook-ui
    ports:
    - containerPort: 80
      protocol: TCP
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-29kgc
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: lima-rancher-desktop
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: kube-api-access-29kgc
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2024-09-18T18:44:03Z"
    status: "True"
    type: PodReadyToStartContainers
  - lastProbeTime: null
    lastTransitionTime: "2024-09-15T15:15:22Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2024-09-18T18:44:03Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2024-09-18T18:44:03Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2024-09-15T15:15:22Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: docker://cb04efc6955cce2c02d5621b00e0bd1947ccb49a7c84b7a5990791eb3e4c557a
    image: gcr.io/heptio-images/ks-guestbook-demo:0.2
    imageID: docker-pullable://gcr.io/heptio-images/ks-guestbook-demo@sha256:e6fbd640820c32c847a53b93eb7b404f25ffb56df1cc16d0711eec3a405d6509
    lastState:
      terminated:
        containerID: docker://314001d07a3c3bfb1fcbe3e4a759b21e74d97085723df58f3824ab1fb964a633
        exitCode: 137
        finishedAt: "2024-09-17T10:27:50Z"
        reason: Error
        startedAt: "2024-09-17T10:16:28Z"
    name: guestbook-ui
    ready: true
    restartCount: 2
    started: true
    state:
      running:
        startedAt: "2024-09-18T18:44:03Z"
  hostIP: 192.168.5.15
  hostIPs:
  - ip: 192.168.5.15
  phase: Running
  podIP: 10.42.0.55
  podIPs:
  - ip: 10.42.0.55
  qosClass: BestEffort
  startTime: "2024-09-15T15:15:22Z"
